#!/bin/sh

# 使用于RAMIPS架构AP

# 修改root密码
sed -i '/root/d' /etc/shadow
sed -i '1i\root:$1$jy0vKzHj$x0SPe/UmNxsePtAyIs4gd0:19266:0:99999:7:::' /etc/shadow #12345678

# 配置系统时区
uci set system.@system[0].hostname='LemonadeWrt-YSUEagle'
uci set system.@system[0].zonename='Asia/Shanghai'
uci set system.@system[0].timezone='CST-8'
uci set system.ntp.server=''
uci add_list system.ntp.server='ntp.aliyun.com'
uci add_list system.ntp.server='time.ustc.edu.cn'
uci commit system

# 配置防火墙
uci set firewall.@zone[0].network='lan'
uci set firewall.@zone[0].input='ACCEPT'
uci set firewall.@zone[1].output='ACCEPT'
uci set firewall.@zone[1].forward='ACCEPT'
uci add firewall rule
uci set firewall.@rule[-1].name='Allow-AP-Web'
uci set firewall.@rule[-1].src='wan'
uci set firewall.@rule[-1].target='ACCEPT'
uci set firewall.@rule[-1].dest_port='80'
uci commit firewall

# 配置无线
uci set wireless.radio1.country='CN'
uci set wireless.radio1.cell_density='1'
uci set wireless.radio1.channel='auto'
uci set wireless.radio1.htmode='HT20'
uci set wireless.radio1.disabled='0'
uci set wireless.default_radio1.ssid='RoboMaster_2.4Ghz'
uci set wireless.default_radio1.encryption='psk2'
uci set wireless.default_radio1.key='12345678'
uci set wireless.default_radio1.network='lan'
uci set wireless.radio0.country='CN'
uci set wireless.radio0.cell_density='0'
uci set wireless.radio0.channel='157'
uci set wireless.radio0.htmode='VHT80'
uci set wireless.radio0.disabled='0'
uci set wireless.default_radio0.ssid='RoboMaster_5Ghz'
uci set wireless.default_radio0.encryption='psk2'
uci set wireless.default_radio0.key='12345678'
uci set wireless.default_radio0.network='lan'
uci commit wireless

#详见： https://openwrt.org/docs/guide-developer/uci-defaults
exit 0
