#!/bin/sh

# 使用于RAMIPS架构AP

# 修改root密码
sed -i '/root/d' /etc/shadow
sed -i '1i\root:$1$jy0vKzHj$x0SPe/UmNxsePtAyIs4gd0:19266:0:99999:7:::' /etc/shadow #12345678

# 配置系统时区
uci set system.@system[0].hostname='AP-WhoIsMe'
uci set system.@system[0].zonename='Asia/Shanghai'
uci set system.@system[0].timezone='CST-8'
uci set system.ntp.server=''
uci add_list system.ntp.server='ntp.aliyun.com'
uci add_list system.ntp.server='time.ustc.edu.cn'
uci commit system

# 配置网桥端口
uci del network.@device[-1]
uci add network device
uci set network.@device[-1].name='br-lan'
uci set network.@device[-1].type='bridge'
uci add_list network.@device[-1].ports='lan1'
uci add_list network.@device[-1].ports='lan2'
uci add_list network.@device[-1].ports='lan3'
uci add_list network.@device[-1].ports='lan4'
uci add_list network.@device[-1].ports='wan'
uci commit network
# 配置局域网(LAN)接口
uci del network.lan
uci add network interface
uci set network.@interface[-1].proto='static'
uci set network.@interface[-1].ipaddr='192.168.254.1'
uci set network.@interface[-1].netmask='255.255.255.0'
uci set network.@interface[-1].ip6assign='64'
uci set network.@interface[-1].device='br-lan'
uci rename network.@interface[-1]='lan'
uci commit network
# 配置上联(WAN)接口
uci del network.wan
uci add network interface
uci set network.@interface[-1].proto='dhcp'
uci set network.@interface[-1].device='br-lan'
uci rename network.@interface[-1]='wan'
uci commit network
# 配置上联(WAN6)接口
uci del network.wan6
uci add network interface
uci set network.@interface[-1].proto='dhcpv6'
uci set network.@interface[-1].device='br-lan'
uci set network.@interface[-1].reqaddress='try'
uci set network.@interface[-1].reqprefix='auto'
uci rename network.@interface[-1]='wan6'
uci commit network

# 配置DHCP
uci del dhcp.lan
uci del dhcp.wan
uci del dhcp.wan6
uci commit dhcp

# 配置防火墙
uci set firewall.@zone[0].network='lan'
uci set firewall.@zone[0].input='ACCEPT'
uci set firewall.@zone[1].output='ACCEPT'
uci set firewall.@zone[1].forward='ACCEPT'
uci add firewall rule
uci set firewall.@rule[-1].name='Allow-AP-Web'
uci set firewall.@rule[-1].src='wan'
uci set firewall.@rule[-1].target='ACCEPT'
uci set firewall.@rule[-1].dest_port='80'
uci add firewall rule
uci set firewall.@rule[-1].name='Allow-AP-SSH'
uci set firewall.@rule[-1].src='wan'
uci set firewall.@rule[-1].target='ACCEPT'
uci set firewall.@rule[-1].dest_port='22'
uci commit firewall

# 配置无线
uci set wireless.radio0.country='CN'
uci set wireless.radio0.cell_density='1'
uci set wireless.radio0.channel='auto'
uci set wireless.radio0.htmode='HT40'
uci set wireless.radio0.disabled='0'
uci set wireless.default_radio0.ssid='LemonadeAP'
uci set wireless.default_radio0.encryption='psk2'
uci set wireless.default_radio0.key='12345678'
uci set wireless.default_radio0.network='br-lan'
uci set wireless.radio1.country='CN'
uci set wireless.radio1.cell_density='0'
uci set wireless.radio1.channel='149'
uci set wireless.radio1.htmode='VHT80'
uci set wireless.radio1.disabled='0'
uci set wireless.default_radio1.ssid='LemonadeAP-5G'
uci set wireless.default_radio1.encryption='psk2'
uci set wireless.default_radio1.key='12345678'
uci set wireless.default_radio1.network='br-lan'
uci commit wireless

#详见： https://openwrt.org/docs/guide-developer/uci-defaults
exit 0
