#!/bin/sh /etc/rc.common
# modified on 2022/02/07

USE_PROCD=1
START=99

start_service() {
         procd_open_instance frpC
         procd_set_param command /usr/bin/frpc -c /etc/config/frp/frpc.ini

         # respawn automatically if something died, be careful if you have an alternative process supervisor
         # if process dies sooner than respawn_threshold, it is considered crashed and after 5 retries the service is stopped
         procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}

         procd_close_instance
}
