#!/bin/sh

#可以直接通过uci的接口修改配置
#比如配置系统时区
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

# 比如配置无线相关
uci set wireless.radio0.cell_density='0'
uci set wireless.default_radio0.ssid='ax1800'
uci set wireless.default_radio0.encryption='psk2'
uci set wireless.default_radio0.key='12345678'
uci set wireless.radio1.cell_density='0'
uci set wireless.default_radio1.ssid='ax1800'
uci set wireless.default_radio1.encryption='psk2'
uci set wireless.default_radio1.key='12345678'
uci commit wireless


#比如配置lan口和wan口
uci set network.lan.ipaddr="192.168.0.1"
uci set network.wan.proto="pppoe" 
uci set network.wan.username="账号"
uci set network.wan.password="密码"
uci commit network


#比如配置 uhttpd 
uci del uhttpd.main.listen_http
uci del uhttpd.main.listen_https
uci add_list uhttpd.main.listen_http=[::]:1089
uci add_list uhttpd.main.listen_http=0.0.0.0:1089
uci add_list uhttpd.main.listen_https=[::]:1443
uci add_list uhttpd.main.listen_https=0.0.0.0:1443
uci set uhttpd.main.rfc1918_filter=0
uci set uhttpd.main.cert=/etc/ssl/certs/certificate.cer
uci set uhttpd.main.key=/etc/ssl/certs/private.key
uci set uhttpd.main.redirect_https=1
uci commit uhttpd


#也可以通过直接修改配置文件的方式来修改配置
#比如修改root默认密码和设置证书登陆的公钥
sed -i '/root/d' /etc/shadow
sed -i '1i\root:$1$G.elgsxV$IBS8iGDyioldPta4rAH0h0:19065:0:99999:7:::' /etc/shadow
echo 'ssh-rsa 共钥' > /etc/dropbear/authorized_keys

####################

#### 大量其他配置 ####

####################

#结束一定要返回 0 只有返回0后，该文件在首次执行后才会被删除
#详见： https://openwrt.org/docs/guide-developer/uci-defaults
exit 0
